ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "gscAccountId" TEXT;
ALTER TABLE "Report" ADD COLUMN IF NOT EXISTS "gscSiteUrl" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "defaultGscAccountId" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "defaultGscSiteUrl" TEXT;
