services:
  web:
    image: registry.gitlab.atwinta.ru/atwinta/internal/atwinta-promotion/aiprojects/reports:${TAG:-stage}
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
      - TOPVISOR_BASE_URL=${TOPVISOR_BASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_SECRET_KEY=${OPENAI_SECRET_KEY}
      - NEXT_PUBLIC_APP_URL=https://${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.r${APP_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.r${APP_NAME}.tls=true
      - traefik.http.routers.r${APP_NAME}.tls.certresolver=resolver
      - traefik.http.routers.r${APP_NAME}.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.r${APP_NAME}.entrypoints=websecure
      - traefik.http.services.s${APP_NAME}.loadbalancer.server.port=${EXPOSED_PORT:-3000}
      - traefik.docker.network=${DEF_NETWORK:-traefik_main}
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresseo_data:/var/lib/postgresql

volumes:
  postgresseo_data:

networks:
  default:
    external: true
    name: ${DEF_NETWORK:-traefik_main}
